print('== Cadastro da Escola ==')
nome = input('Digite o nome:  ')
print('Bem vindo(a) '+nome)
lazer = input('O que gosta de fazer?')
print(lazer)
cor = input('Qual é a sua cor favorita?')
print('A cor preferida é '+cor)
time = input('Qual o seu time?')
print('Time do Coração: '+time)