/* ==========================================================================
   FUNKO STORE — Base de dados dos produtos
   Fonte única de verdade: todas as páginas (catálogo, promoções, home,
   página de produto e busca) leem deste array. Isso simula como uma loja
   real puxaria os produtos de um banco de dados / API.
   ========================================================================== */

const FUNKO_PRODUCTS = [
  {
    id: "mewtwo-581",
    numero: "581",
    nome: "Mewtwo",
    franquia: "Pokémon",
    categoria: "games",
    preco: 125.04,
    precoAntigo: null,
    imagem: "MewFunko.webp",
    avaliacao: 4.8,
    avaliacoesQtd: 214,
    estoque: 18,
    selos: ["novidade"],
    descricao: "O Pokémon lendário criado em laboratório ganha vida em vinil. Mewtwo surge em pose de combate, com direito ao brilho psíquico característico pintado à mão nos detalhes.",
  },
  {
    id: "sanji-1773",
    numero: "1773",
    nome: "Sanji",
    franquia: "One Piece",
    categoria: "anime",
    preco: 104.07,
    precoAntigo: null,
    imagem: "SanjiFunko.webp",
    avaliacao: 4.9,
    avaliacoesQtd: 341,
    estoque: 27,
    selos: ["mais-vendido"],
    descricao: "O cozinheiro dos Chapéus de Palha em sua clássica pose de chute em chamas. Um item essencial para qualquer fã da Grand Line.",
  },
  {
    id: "iron-man-1421",
    numero: "1421",
    nome: "Iron Man",
    franquia: "Marvel",
    categoria: "marvel",
    preco: 149.99,
    precoAntigo: null,
    imagem: "IronFunko.webp",
    avaliacao: 4.7,
    avaliacoesQtd: 502,
    estoque: 40,
    selos: ["mais-vendido"],
    descricao: "Tony Stark em sua armadura mais icônica. Detalhes metalizados e reator arc iluminado na pintura para um acabamento premium.",
  },
  {
    id: "arthur-boyle-978",
    numero: "978",
    nome: "Arthur Boyle",
    franquia: "Fire Force",
    categoria: "anime",
    preco: 119.90,
    precoAntigo: null,
    imagem: "ArthurFunko.webp",
    avaliacao: 4.5,
    avaliacoesQtd: 88,
    estoque: 12,
    selos: [],
    descricao: "O autoproclamado Cavaleiro em Chamas empunha sua espada em pose de batalha. Peça de vinil oficial licenciada da série Fire Force.",
  },
  {
    id: "shoto-todoroki-1258",
    numero: "1258",
    nome: "Shoto Todoroki",
    franquia: "My Hero Academia",
    categoria: "anime",
    preco: 109.90,
    precoAntigo: null,
    imagem: "ShotoFunko.jpg",
    avaliacao: 4.9,
    avaliacoesQtd: 276,
    estoque: 22,
    selos: ["mais-vendido"],
    descricao: "Metade gelo, metade fogo. Todoroki é retratado com seus dois elementos em plena ativação, um dos itens mais procurados da linha MHA.",
  },
  {
    id: "mickey-fantasia-990",
    numero: "990",
    nome: "Sorcerer Mickey",
    franquia: "Disney Fantasia",
    categoria: "disney",
    preco: 139.90,
    precoAntigo: null,
    imagem: "MickeyFunko.jpg",
    avaliacao: 4.8,
    avaliacoesQtd: 190,
    estoque: 15,
    selos: [],
    descricao: "O clássico Mickey Feiticeiro de Fantasia (1940), com chapéu pontudo e capa estrelada. Peça de coleção atemporal da Disney.",
  },
  {
    id: "overhaul-788",
    numero: "788",
    nome: "Overhaul",
    franquia: "My Hero Academia",
    categoria: "anime",
    preco: 129.90,
    precoAntigo: null,
    imagem: "OverhaulFunko.avif",
    avaliacao: 4.6,
    avaliacoesQtd: 71,
    estoque: 9,
    selos: ["exclusivo"],
    descricao: "O líder da Yakuza Shie Hassaikai em sua máscara característica. Edição de tiragem limitada para colecionadores.",
  },
  {
    id: "yoda-277",
    numero: "277",
    nome: "Yoda",
    franquia: "Star Wars",
    categoria: "star-wars",
    preco: 115.90,
    precoAntigo: null,
    imagem: "YodaFunko.jpg",
    avaliacao: 4.9,
    avaliacoesQtd: 623,
    estoque: 50,
    selos: ["mais-vendido"],
    descricao: "O grande Mestre Jedi, sabedoria em forma de vinil. Um dos personagens mais colecionados de toda a linha Star Wars.",
  },
  {
    id: "bond-forger-1953",
    numero: "1953",
    nome: "Bond Forger",
    franquia: "Spy x Family",
    categoria: "anime",
    preco: 125.90,
    precoAntigo: null,
    imagem: "BondFunko.webp",
    avaliacao: 4.7,
    avaliacoesQtd: 154,
    estoque: 24,
    selos: ["novidade"],
    descricao: "O cachorro precognitivo da família Forger, orelhas para cima e pronto para proteger Anya. Item fofo e muito procurado.",
  },
  {
    id: "goku-1699",
    numero: "1699",
    nome: "Goku",
    franquia: "Dragon Ball Super",
    categoria: "anime",
    preco: 139.90,
    precoAntigo: null,
    imagem: "GokuFunko.webp",
    avaliacao: 4.9,
    avaliacoesQtd: 410,
    estoque: 30,
    selos: ["novidade", "mais-vendido"],
    descricao: "Son Goku em sua pose de luta clássica. Faz parte da nova leva de lançamentos de Dragon Ball Super que acabou de chegar à loja.",
  },
  {
    id: "toshiro-1875",
    numero: "1875",
    nome: "Toshiro Hitsugaya",
    franquia: "Bleach",
    categoria: "anime",
    preco: 124.90,
    precoAntigo: null,
    imagem: "ToshiroFunko.webp",
    avaliacao: 4.8,
    avaliacoesQtd: 132,
    estoque: 17,
    selos: ["novidade"],
    descricao: "O capitão prodígio do Gotei 13 com sua zanpakuto Hyorinmaru. Parte da nova coleção dos Capitães de Bleach.",
  },
  {
    id: "jotaro-1441",
    numero: "1441",
    nome: "Jotaro Kujo",
    franquia: "JoJo's Bizarre Adventure",
    categoria: "anime",
    preco: 134.90,
    precoAntigo: null,
    imagem: "Joestar.jpg",
    avaliacao: 4.9,
    avaliacoesQtd: 201,
    estoque: 20,
    selos: ["novidade"],
    descricao: "Jotaro Kujo com seu boné e jaqueta característicos. Um clássico simplesmente bizarro para completar sua coleção de anime.",
  },
  {
    id: "kafka-1616",
    numero: "1616",
    nome: "Kafka Hibino",
    franquia: "Kaiju No. 8",
    categoria: "anime",
    preco: 119.90,
    precoAntigo: null,
    imagem: "KaijuFunko.webp",
    avaliacao: 4.6,
    avaliacoesQtd: 58,
    estoque: 14,
    selos: ["novidade", "pre-venda"],
    descricao: "Kafka Hibino, o novo herói de Kaiju No. 8, disponível para pré-venda. Garanta o seu antes do lançamento oficial esgotar.",
  },
  {
    id: "alphonse-elric-392",
    numero: "392",
    nome: "Alphonse Elric",
    franquia: "Fullmetal Alchemist",
    categoria: "anime",
    preco: 62.52,
    precoAntigo: 125.04,
    imagem: "AlFunko.jpg",
    avaliacao: 4.8,
    avaliacoesQtd: 167,
    estoque: 11,
    selos: ["promocao"],
    descricao: "A armadura vazia que guarda a alma de Alphonse, fielmente reproduzida em vinil com o acabamento metálico característico.",
  },
  {
    id: "scrooge-mcduck-312",
    numero: "312",
    nome: "Scrooge McDuck",
    franquia: "DuckTales",
    categoria: "disney",
    preco: 52.04,
    precoAntigo: 104.07,
    imagem: "PatinhasFunko.jpg",
    avaliacao: 4.7,
    avaliacoesQtd: 96,
    estoque: 8,
    selos: ["promocao"],
    descricao: "Tio Patinhas com cartola, monóculo e bengala. Um clássico da Disney com desconto imperdível por tempo limitado.",
  },
  {
    id: "akuma-203",
    numero: "203",
    nome: "Akuma",
    franquia: "Street Fighter",
    categoria: "games",
    preco: 74.99,
    precoAntigo: 149.99,
    imagem: "AkumaFunko.jpg",
    avaliacao: 4.6,
    avaliacoesQtd: 73,
    estoque: 6,
    selos: ["promocao", "ultimas-unidades"],
    descricao: "O mestre do Shun Goku Satsu em pose de ataque. Últimas unidades com metade do preço.",
  },
  {
    id: "harry-potter-01",
    numero: "01",
    nome: "Harry Potter",
    franquia: "Harry Potter",
    categoria: "filmes",
    preco: 59.95,
    precoAntigo: 119.90,
    imagem: "HarryPotter.jpg",
    avaliacao: 4.9,
    avaliacoesQtd: 388,
    estoque: 33,
    selos: ["promocao"],
    descricao: "O bruxo mais famoso do cinema com sua varinha e capa de Hogwarts. Figura número 01 da linha, um item histórico da Funko.",
  },
  {
    id: "sakamoto-2058",
    numero: "2058",
    nome: "Taro Sakamoto",
    franquia: "Sakamoto Days",
    categoria: "anime",
    preco: 54.95,
    precoAntigo: 109.90,
    imagem: "SakamotoFunko.jpg",
    avaliacao: 4.7,
    avaliacoesQtd: 61,
    estoque: 10,
    selos: ["promocao", "novidade"],
    descricao: "O ex-assassino mais letal (e mais gente boa) do mangá, agora atrás do balcão da mercearia. Lançamento recente com preço promocional.",
  },
  {
    id: "swampfire-1202",
    numero: "1202",
    nome: "Swampfire",
    franquia: "Ben 10 Alien Force",
    categoria: "filmes",
    preco: 69.95,
    precoAntigo: 139.90,
    imagem: "FogoFunko.jpg",
    avaliacao: 4.4,
    avaliacoesQtd: 39,
    estoque: 7,
    selos: ["promocao"],
    descricao: "Um dos aliens mais queridos do Omnitrix, em chamas verdes características. Traz nostalgia pura para fãs da série.",
  },
  {
    id: "metal-sonic-1118",
    numero: "1118",
    nome: "Neo Metal Sonic",
    franquia: "Sonic the Hedgehog",
    categoria: "games",
    preco: 64.95,
    precoAntigo: 129.90,
    imagem: "MetalFunko.jpg",
    avaliacao: 4.8,
    avaliacoesQtd: 145,
    estoque: 19,
    selos: ["promocao"],
    descricao: "A versão aprimorada do rival robótico de Sonic, em acabamento metálico vermelho e prata. Peça cobiçada pelos fãs de games.",
  },
  {
    id: "proto-man-104",
    numero: "104",
    nome: "Proto Man",
    franquia: "Mega Man",
    categoria: "games",
    preco: 57.95,
    precoAntigo: 115.90,
    imagem: "ProtoFunko.jpg",
    avaliacao: 4.5,
    avaliacoesQtd: 44,
    estoque: 5,
    selos: ["promocao", "ultimas-unidades"],
    descricao: "O misterioso irmão de Mega Man, cachecol ao vento e canhão de plasma em punho. Últimas unidades em promoção.",
  },
  {
    id: "johnny-lawrence-970",
    numero: "970",
    nome: "Johnny Lawrence",
    franquia: "Cobra Kai",
    categoria: "filmes",
    preco: 62.95,
    precoAntigo: 125.90,
    imagem: "JohnnyFunko.jpg",
    avaliacao: 4.6,
    avaliacoesQtd: 83,
    estoque: 13,
    selos: ["promocao"],
    descricao: "O sensei da Cobra Kai em sua clássica jaqueta jeans. Golpe primeiro, sem piedade — e com desconto de 50%.",
  },
];

/* Metadados de categoria usados nos filtros e menus */
const FUNKO_CATEGORIAS = [
  { slug: "anime", nome: "Anime" },
  { slug: "games", nome: "Games" },
  { slug: "marvel", nome: "Marvel" },
  { slug: "star-wars", nome: "Star Wars" },
  { slug: "disney", nome: "Disney" },
  { slug: "filmes", nome: "Filmes & TV" },
];

const FUNKO_SELOS_LABEL = {
  "novidade": "Novidade",
  "mais-vendido": "Mais vendido",
  "exclusivo": "Exclusivo",
  "promocao": "Promoção",
  "pre-venda": "Pré-venda",
  "ultimas-unidades": "Últimas unidades",
};

/* Helpers de acesso aos dados, usados por várias páginas */
function funkoGetProductById(id) {
  return FUNKO_PRODUCTS.find(p => p.id === id) || null;
}

function funkoFormatBRL(value) {
  return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
}

function funkoDiscountPercent(product) {
  if (!product.precoAntigo || product.precoAntigo <= product.preco) return 0;
  return Math.round(100 - (product.preco / product.precoAntigo) * 100);
}

function funkoRelatedProducts(product, limit = 4) {
  return FUNKO_PRODUCTS
    .filter(p => p.id !== product.id && (p.franquia === product.franquia || p.categoria === product.categoria))
    .slice(0, limit);
}
